'use client'

import Link from 'next/link'

const SECTIONS = [
  {
    n: '01',
    title: 'About LagosLandCheck',
    body: `LagosLandCheck ("we," "us," "our," or "the Service") is an online pre-screening intelligence service for property in Lagos State, Nigeria. We are accessible at lagoslandcheck.com.

The Service is operated from Lagos, Nigeria. We are presently an unincorporated business operated by an individual. Once registered with the Corporate Affairs Commission of Nigeria, this section will be updated with our registration number and corporate name.

For all communications regarding these Terms or any other matter, contact us at support@lagoslandcheck.com.`,
  },
  {
    n: '02',
    title: 'What the Service does — and what it is NOT',
    body: `LagosLandCheck runs six automated checks on Lagos coordinates you submit:

(a) Satellite imagery analysis using publicly available Google Maps Static API images combined with GPT-4o visual analysis;
(b) Lagos State Gazette and government acquisition lookup;
(c) Flood and drainage risk assessment based on Lagos State flood maps;
(d) Court litigation search across published Lagos State Judiciary cause lists;
(e) Land Use Charge status lookup;
(f) Fraud zone and Omo Onile alert database lookup.

The output of these checks is delivered as a PDF report and email summary, priced at ₦2,500 per coordinate.

CRITICAL: This Service is pre-screening intelligence ONLY. It is NOT:
• Legal advice
• A formal Land Registry title search
• A substitute for engaging a licensed Nigerian property lawyer
• A guarantee of clean title, free passage, or any other property right
• A surveyor's report or boundary verification
• A government-issued certificate of any kind

You agree that you will engage a licensed Nigerian property lawyer to conduct a full Land Registry search before completing any property transaction, regardless of the findings in any report generated by this Service.`,
  },
  {
    n: '03',
    title: 'Accuracy & limitations',
    body: `Our checks rely on publicly available data sources, satellite imagery, and automated analysis. We make every reasonable effort to ensure accuracy, but you acknowledge:

(a) Public registries (gazettes, court cause lists, LUC records) may be incomplete, out of date, or inaccurate at source. We cannot verify or correct source data.

(b) Satellite imagery is captured by third parties and may be days, weeks, or months old. Visible features in imagery may have changed since capture.

(c) Our AI-based satellite analysis (GPT-4o) is a probabilistic tool. While generally accurate for identifying buildings vs vacant land, it can make errors — especially on ambiguous imagery, areas with heavy tree cover, or recently developed sites.

(d) A "CLEAR" result on any check does NOT mean no issue exists. It means no issue was detected by our automated systems. The absence of evidence is not evidence of absence.

(e) A "CAUTION" or "HIGH RISK" result is a prompt for further investigation, not a definitive judgment. Always consult a lawyer.

You agree to use the Service's output as a starting point for due diligence, never as a final determination.`,
  },
  {
    n: '04',
    title: 'Your obligations as a user',
    body: `When using the Service, you agree to:

(a) Submit only coordinates and addresses you have a lawful interest in verifying (e.g. property you are considering buying, properties on which you are advising as a lawyer or estate agent).

(b) Not use the Service for stalking, harassment, surveillance of private individuals, or any other unlawful purpose.

(c) Not attempt to scrape, automate, reverse engineer, or otherwise abuse the Service.

(d) Not resell or redistribute reports without our written permission. Reports are licensed to you for personal due diligence on the specific property checked.

(e) Provide accurate email and contact information when required for report delivery.

(f) Not impersonate any person or entity when contacting us or using the Service.

We reserve the right to suspend or terminate access for any user who violates these obligations.`,
  },
  {
    n: '05',
    title: 'Payment & pricing',
    body: `Standard verification reports cost ₦2,500 NGN per coordinate. Prices are displayed in Nigerian Naira (₦). We may change prices from time to time; the price displayed at the time of payment is the price you will be charged.

All payments are processed by Paystack (paystack.com), a licensed Nigerian payment processor. We do not store, transmit, or have access to your card details — these are handled entirely by Paystack under their security standards.

Payment is a one-time charge. There are no recurring fees, subscriptions, or hidden charges. If you see unexpected charges on your statement, contact Paystack support immediately.

Refunds are governed by our Refund Policy at lagoslandcheck.com/refund-policy.`,
  },
  {
    n: '06',
    title: 'Intellectual property',
    body: `(a) The LagosLandCheck name, logo, dossier design, and website code are our intellectual property. You may not copy, reproduce, or use these for any purpose without our written permission.

(b) Reports generated by the Service are licensed to you for personal use in due diligence for the specific property checked. You may share a report with your lawyer, your spouse, your business partner, or any other party assisting your due diligence. You may not resell reports, post them publicly, or use them for commercial republication.

(c) The underlying data (gazette records, court records, satellite imagery, etc.) is sourced from public registries and third-party providers (Google, Lagos State Government, etc.). We do not claim ownership of source data.

(d) If you submit feedback, suggestions, or feature requests, you grant us a perpetual, royalty-free right to use that feedback to improve the Service.`,
  },
  {
    n: '07',
    title: 'Liability & disclaimers',
    body: `READ THIS SECTION CAREFULLY. IT LIMITS OUR LIABILITY TO YOU.

The Service is provided "AS IS" and "AS AVAILABLE." We make no warranties, express or implied, regarding the Service, its output, or its fitness for any particular purpose.

To the maximum extent permitted by applicable Nigerian law:

(a) We are not liable for any property loss, financial loss, transaction loss, or consequential loss arising from your reliance on a report. You agree that you have engaged or will engage a licensed Nigerian property lawyer to conduct independent verification before any transaction.

(b) Our total cumulative liability to you for any claim related to the Service is limited to the amount you paid us for the specific report giving rise to the claim — typically ₦2,500.

(c) We are not liable for losses caused by inaccurate or incomplete source data (public registries, satellite imagery providers, etc.), nor for losses caused by AI analysis errors.

(d) We are not liable for losses caused by your failure to engage a property lawyer before completing a transaction.

(e) Nothing in these Terms excludes liability that cannot be excluded under Nigerian law (e.g., liability for fraud, willful misconduct, or gross negligence).`,
  },
  {
    n: '08',
    title: 'Indemnification',
    body: `You agree to indemnify and hold harmless LagosLandCheck, its operators, and its service providers (Paystack, Resend, Supabase, OpenAI, Google, Vercel) from any claims, losses, or expenses arising from:

(a) Your misuse of the Service or violation of these Terms.

(b) Your use of report findings to make or recommend a property transaction without engaging a licensed lawyer.

(c) Any false or unlawful coordinate or information you submit.

(d) Any third party's claim that you infringed their rights using information from a report.`,
  },
  {
    n: '09',
    title: 'Termination',
    body: `We may suspend or terminate your access to the Service at any time for violation of these Terms, abuse, suspected fraud, or any other reason we consider reasonable. We will provide notice via the email associated with your purchases where practical.

You may stop using the Service at any time. Reports already delivered remain accessible at the secure links provided in your delivery emails.

Termination does not affect:
• Refund eligibility for legitimate refund requests (see Refund Policy)
• Liability limitations under Section 07
• Indemnification obligations under Section 08`,
  },
  {
    n: '10',
    title: 'Changes to these Terms',
    body: `We may update these Terms from time to time. Material changes will be notified by:

(a) Updating the "Last updated" date at the top of this page;
(b) Posting a notice on the homepage for at least 14 days;
(c) Where practical, emailing past customers about significant changes.

Your continued use of the Service after changes constitutes acceptance of the updated Terms. If you do not agree to updated Terms, stop using the Service.`,
  },
  {
    n: '11',
    title: 'Governing law & disputes',
    body: `These Terms are governed by the laws of the Federal Republic of Nigeria. Any dispute arising from these Terms or your use of the Service will be subject to the exclusive jurisdiction of the courts of Lagos State, Nigeria.

Before initiating legal proceedings, you agree to first contact us in good faith at support@lagoslandcheck.com to attempt resolution. Most disputes are resolvable in a single email exchange.`,
  },
  {
    n: '12',
    title: 'Contact',
    body: `For questions, concerns, or notices about these Terms:

Email: support@lagoslandcheck.com
Response time: within 24 hours, Monday–Saturday (West Africa Time)

For payment disputes, refund requests, or chargebacks, please email us BEFORE initiating a Paystack chargeback — direct resolution is faster and avoids the formal dispute process.`,
  },
]

export default function TermsPage() {
  return (
    <div style={{ fontFamily: "'Syne',-apple-system,sans-serif", background: '#F8FAF9', minHeight: '100vh' }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;500;600;700;800&family=Inter:wght@400;500;600&family=Lora:ital,wght@0,600;1,600&family=JetBrains+Mono:wght@400;500;600&display=swap');
        *{box-sizing:border-box;margin:0;padding:0}
        @keyframes fadeUp{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}
        .appear{animation:fadeUp .4s ease both}
      `}</style>

      <nav style={{
        background: '#07382C',
        padding: '0.75rem 1.25rem',
        display: 'flex',
        alignItems: 'center',
        gap: 10,
        boxShadow: '0 2px 12px rgba(0,0,0,0.2)',
      }}>
        <Link href="/" style={{
          background: 'rgba(255,255,255,0.12)',
          borderRadius: 7,
          padding: '5px 12px',
          color: '#fff',
          fontSize: 12,
          textDecoration: 'none',
        }}>← Home</Link>
        <div style={{ width: 28, height: 28, background: '#0A5C45', borderRadius: 7, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <svg width="13" height="13" viewBox="0 0 24 24" fill="white"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>
        </div>
        <span style={{ fontWeight: 700, fontSize: 14, color: '#fff' }}>Terms of Service</span>
      </nav>

      <section style={{
        background: '#07382C',
        color: '#fff',
        padding: '48px 24px 64px',
        position: 'relative',
        borderBottom: '3px solid #CFAF6E',
      }}>
        <div style={{
          position: 'absolute',
          bottom: -3,
          left: 0,
          right: 0,
          height: 3,
          background: 'linear-gradient(90deg,#CFAF6E 0%,#CFAF6E 30%,transparent 30%,transparent 70%,#CFAF6E 70%)',
        }} />
        <div style={{ maxWidth: 760, margin: '0 auto' }}>
          <div style={{
            fontFamily: 'Menlo,Consolas,monospace',
            fontSize: 10,
            color: '#CFAF6E',
            letterSpacing: '2.5px',
            marginBottom: 14,
            fontWeight: 700,
          }}>
            ─── LEGAL · TERMS OF SERVICE
          </div>
          <h1 style={{
            fontFamily: "'Lora',serif",
            fontSize: 'clamp(28px,5vw,42px)',
            fontWeight: 600,
            lineHeight: 1.15,
            letterSpacing: '-1px',
            marginBottom: 14,
          }}>
            Terms of Service
          </h1>
          <p style={{
            fontSize: 14,
            color: 'rgba(255,255,255,0.65)',
            lineHeight: 1.65,
            maxWidth: 580,
          }}>
            By using lagoslandcheck.com, you agree to these Terms. Read them carefully — they limit our liability and set out your obligations as a user.
          </p>
          <p style={{
            fontSize: 13,
            color: 'rgba(255,255,255,0.5)',
            lineHeight: 1.65,
            marginTop: 12,
            fontFamily: 'Menlo,Consolas,monospace',
          }}>
            Effective: {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })} · Last updated: {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
          </p>
        </div>
      </section>

      <div style={{ maxWidth: 760, margin: '0 auto', padding: '0 16px' }}>
        <div className="appear" style={{
          background: '#fff',
          borderRadius: 12,
          border: '1px solid #E5E7EB',
          marginTop: -32,
          padding: '28px 32px',
          boxShadow: '0 4px 24px rgba(0,0,0,0.06)',
          position: 'relative',
          zIndex: 2,
          marginBottom: 28,
        }}>
          <div style={{
            display: 'flex',
            alignItems: 'center',
            gap: 10,
            paddingBottom: 14,
            borderBottom: '1px solid #E5E7EB',
            marginBottom: 18,
          }}>
            <div style={{
              width: 32, height: 32, borderRadius: 8, background: '#07382C',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              color: '#CFAF6E', fontFamily: 'Menlo,monospace', fontWeight: 700, fontSize: 13,
            }}>§</div>
            <div style={{ fontSize: 13, color: '#5C6B7A', lineHeight: 1.5 }}>
              <strong style={{ color: '#1A2332' }}>Quick summary:</strong> We provide pre-screening intelligence, not legal advice. Always use a property lawyer for the final title search. Our liability is capped at the price you paid (₦2,500).
            </div>
          </div>

          <p style={{ fontSize: 13, color: '#5C6B7A', lineHeight: 1.6 }}>
            These are the legal terms governing your use of LagosLandCheck. They are written to be readable — but they are still a binding agreement between you and us. By using the Service, you accept them.
          </p>
        </div>

        {SECTIONS.map(s => (
          <div key={s.n} className="appear" style={{
            background: '#fff',
            borderRadius: 10,
            border: '1px solid #E5E7EB',
            padding: '24px 28px',
            marginBottom: 14,
          }}>
            <div style={{
              display: 'flex',
              alignItems: 'baseline',
              gap: 14,
              marginBottom: 12,
              paddingBottom: 12,
              borderBottom: '1px dashed #E5E7EB',
            }}>
              <span style={{
                fontFamily: 'Menlo,Consolas,monospace',
                fontSize: 11,
                color: '#CFAF6E',
                fontWeight: 700,
                letterSpacing: '1px',
              }}>{s.n}</span>
              <h2 style={{
                fontFamily: "'Lora',serif",
                fontSize: 18,
                fontWeight: 600,
                color: '#1A2332',
                letterSpacing: '-0.3px',
              }}>{s.title}</h2>
            </div>
            <div style={{
              fontSize: 13.5,
              color: '#374151',
              lineHeight: 1.75,
              whiteSpace: 'pre-line',
            }}>{s.body}</div>
          </div>
        ))}

        <div style={{
          background: '#07382C',
          color: '#fff',
          borderRadius: 10,
          padding: '24px 28px',
          marginTop: 24,
          marginBottom: 40,
          textAlign: 'center',
        }}>
          <div style={{
            fontFamily: 'Menlo,Consolas,monospace',
            fontSize: 10,
            color: '#CFAF6E',
            letterSpacing: '2px',
            marginBottom: 10,
          }}>QUESTIONS ABOUT THESE TERMS?</div>
          <a href="mailto:support@lagoslandcheck.com" style={{
            color: '#fff',
            fontSize: 16,
            fontWeight: 600,
            textDecoration: 'none',
            letterSpacing: '-0.2px',
          }}>support@lagoslandcheck.com</a>
          <div style={{
            fontSize: 12,
            color: 'rgba(255,255,255,0.6)',
            marginTop: 6,
            fontFamily: 'Menlo,Consolas,monospace',
          }}>Replies within 24h · Monday–Saturday · WAT</div>
        </div>

        <div style={{
          textAlign: 'center',
          padding: '0 0 60px',
          fontSize: 11,
          color: '#9CA3AF',
          fontFamily: 'Menlo,Consolas,monospace',
          lineHeight: 1.8,
        }}>
          See also: <Link href="/refund-policy" style={{ color: '#07382C', textDecoration: 'none' }}>Refund Policy</Link> · <Link href="/privacy" style={{ color: '#07382C', textDecoration: 'none' }}>Privacy Policy</Link><br />
          LagosLandCheck · lagoslandcheck.com
        </div>
      </div>
    </div>
  )
}
